sonar.verbose=true
sonar.projectKey=guiharsh2
sonar.organization=guiharsh2
sonar.projectName=project01-sample-mvn-app
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes